"use client";

import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Loader2, Copy, Check, FileText, Edit2, Play, Eye, Code } from "lucide-react";
import { toast } from "react-hot-toast";
import { sanitizeResumeText } from "@/lib/ai/router";

import { parseResumeIntoBlocks, ResumeBlock, parseLaTeXToPlainText } from "@/lib/export/pdf-document";

// Helper to strip markdown bold/italic tags
function cleanMarkdown(s: string): string {
  return s
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/`/g, "")
    .trim();
}

// Convert blocks to professional LaTeX format code
export function convertBlocksToLaTeX(name: string, contactLine: string, blocks: ResumeBlock[]): string {
  let latex = `% LaTeX Resume generated by FastHire AI
\\documentclass[letterpaper,11pt]{article}
\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}

\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.0in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\textbf{\\Huge ${escapeLaTeX(name)}}} \\\\ \\vspace{4pt}
    \\small ${escapeLaTeX(contactLine)}
\\end{center}

`;

  for (const block of blocks) {
    if (block.type === "name" || block.type === "contact" || block.type === "spacer") {
      continue;
    }

    if (block.type === "section") {
      latex += `\n\\section{${escapeLaTeX(block.text)}}\n`;
    } else if (block.type === "summary") {
      latex += `${escapeLaTeX(block.text)}\\\\\n`;
    } else if (block.type === "skillLine") {
      latex += `\\textbf{${escapeLaTeX(block.label)}}: ${escapeLaTeX(block.value)}\\\\\n`;
    } else if (block.type === "job") {
      latex += `\\vspace{4pt}\n\\textbf{${escapeLaTeX(block.title)}} \\hfill {\\small ${escapeLaTeX(block.dates)}}\\\\\n`;
      latex += `\\textit{${escapeLaTeX(block.company)}}\\\\\n`;
      if (block.bullets.length > 0) {
        latex += "\\begin{itemize}[leftmargin=0.15in, label=\\textbullet]\n";
        for (const bullet of block.bullets) {
          latex += `  \\item ${escapeLaTeX(bullet)}\n`;
        }
        latex += "\\end{itemize}\n\\vspace{-5pt}\n";
      }
    } else if (block.type === "project") {
      latex += `\\vspace{4pt}\n\\textbf{${escapeLaTeX(block.name)}}`;
      if (block.projectUrl) {
        latex += ` \\href{${block.projectUrl}}{${escapeLaTeX(block.projectUrl)}}`;
      }
      if (block.tech) {
        latex += ` \\hfill {\\small \\textit{${escapeLaTeX(block.tech)}}}`;
      }
      latex += "\\\\\n";
      if (block.bullets.length > 0) {
        latex += "\\begin{itemize}[leftmargin=0.15in, label=\\textbullet]\n";
        for (const bullet of block.bullets) {
          latex += `  \\item ${escapeLaTeX(bullet)}\n`;
        }
        latex += "\\end{itemize}\n\\vspace{-5pt}\n";
      }
    } else if (block.type === "education") {
      latex += `\\vspace{4pt}\n\\textbf{${escapeLaTeX(block.degree)}} \\hfill {\\small ${escapeLaTeX(block.dates)}}\\\\\n`;
      latex += `\\textit{${escapeLaTeX(block.school)}} \\hfill {\\small ${escapeLaTeX(block.gpa)}}\\\\\n`;
    } else if (block.type === "bullet") {
      latex += "\\begin{itemize}[leftmargin=0.15in, label=\\textbullet]\n";
      latex += `  \\item ${escapeLaTeX(block.text)}\n`;
      latex += "\\end{itemize}\n\\vspace{-5pt}\n";
    } else if (block.type === "cert") {
      latex += `${escapeLaTeX(block.text)}\\\\\n`;
    } else if (block.type === "link") {
      latex += `\\href{${block.url}}{${escapeLaTeX(block.label)}}\\\\\n`;
    } else if (block.type === "normal") {
      latex += `${escapeLaTeX(block.text)}\\\\\n`;
    }
  }

  latex += "\n\\end{document}\n";
  return latex;
}

function escapeLaTeX(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/~/g, "\\textasciitilde")
    .replace(/\^/g, "\\textasciicircum");
}

interface ResumeViewerProps {
  text: string;
  originalText?: string;
  resumeId: string;
  jobDescription: string;
  onUpdateText?: (newText: string) => void;
  onReScored?: (newScore: number) => void;
  defaultEditMode?: boolean;
}

export default function ResumeViewer({
  text,
  originalText,
  resumeId,
  jobDescription,
  onUpdateText,
  onReScored,
  defaultEditMode
}: ResumeViewerProps) {
  const [currentText, setCurrentText] = useState(text);
  const [isEditing, setIsEditing] = useState(defaultEditMode || false);
  const [viewMode, setViewMode] = useState<"styled" | "latex">("styled");
  const [copied, setCopied] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [docxLoading, setDocxLoading] = useState(false);

  // Live scoring state
  const [liveScore, setLiveScore] = useState<number | null>(null);
  const [scoringLive, setScoringLive] = useState(false);

  useEffect(() => {
    if (defaultEditMode) {
      const blocks = parseResumeIntoBlocks(text);
      const nameBlock = blocks.find(n => n.type === "name");
      const contactBlock = blocks.find(n => n.type === "contact");
      const nameText = nameBlock ? (nameBlock.type === "name" ? nameBlock.text : "Resume Document") : "Resume Document";
      const contactText = contactBlock && contactBlock.type === "contact"
        ? contactBlock.segments.map(s => s.text).join(" | ")
        : "";
      const latex = convertBlocksToLaTeX(nameText, contactText, blocks);
      setCurrentText(latex);
      setIsEditing(true);
    } else {
      setCurrentText(text);
      setIsEditing(false);
    }
    setLiveScore(null);
  }, [text, defaultEditMode]);

  const enterEditMode = () => {
    const blocks = parseResumeIntoBlocks(currentText);
    const nameBlock = blocks.find(n => n.type === "name");
    const contactBlock = blocks.find(n => n.type === "contact");
    const nameText = nameBlock ? (nameBlock.type === "name" ? nameBlock.text : "Resume Document") : "Resume Document";
    const contactText = contactBlock && contactBlock.type === "contact"
      ? contactBlock.segments.map(s => s.text).join(" | ")
      : "";
    const latex = convertBlocksToLaTeX(nameText, contactText, blocks);
    setCurrentText(latex);
    setIsEditing(true);
  };

  const handleCompile = async () => {
    setScoringLive(true);
    try {
      const plainText = parseLaTeXToPlainText(currentText);
      const res = await fetch("/api/score", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeText: plainText, jobDescription })
      });
      if (res.ok) {
        const scoreData = await res.json();
        setLiveScore(scoreData.overall);
        if (onReScored) onReScored(scoreData.overall);
      }
      setCurrentText(plainText);
      setIsEditing(false);
      setViewMode("styled");
      if (onUpdateText) onUpdateText(plainText);
      toast.success("Compiled successfully! Styled preview updated.");
    } catch (err) {
      toast.error("Compilation / scoring failed.");
    } finally {
      setScoringLive(false);
    }
  };

  // Debounced live scoring (800ms)
  useEffect(() => {
    if (!isEditing) return;

    const handler = setTimeout(async () => {
      if (!currentText.trim()) {
        setLiveScore(null);
        return;
      }
      setScoringLive(true);
      try {
        const plainText = parseLaTeXToPlainText(currentText);
        const res = await fetch("/api/score", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ resumeText: plainText, jobDescription })
        });
        if (res.ok) {
          const scoreData = await res.json();
          setLiveScore(scoreData.overall);
        }
      } catch (err) {
        console.error("Live score check failed:", err);
      } finally {
        setScoringLive(false);
      }
    }, 800);

    return () => clearTimeout(handler);
  }, [currentText, isEditing, jobDescription]);

  // Parse blocks for rendering
  const blocks = parseResumeIntoBlocks(currentText);

  // Extract name and contact for header
  const nameBlock = blocks.find(n => n.type === "name");
  const contactBlock = blocks.find(n => n.type === "contact");
  const nameText = nameBlock ? (nameBlock.type === "name" ? nameBlock.text : "Resume Document") : "Resume Document";
  const contactText = contactBlock && contactBlock.type === "contact"
    ? contactBlock.segments.map(s => s.text).join(" | ")
    : "";

  // Set up original words Set for diff highlighting
  const originalClean = (originalText || "").toLowerCase().replace(/[^a-z0-9\s]/g, " ");
  const originalWordsSet = new Set(originalClean.split(/\s+/).filter(Boolean));

  // Word-by-word diff highlighter helper
  const renderHighlightedText = (lineText: string) => {
    if (!originalText || originalWordsSet.size === 0) {
      return <span>{lineText}</span>;
    }
    const parts = lineText.split(/(\s+)/);
    return parts.map((part, idx) => {
      if (/^\s+$/.test(part)) {
        return <span key={idx}>{part}</span>;
      }
      const clean = part.toLowerCase().replace(/[^a-z0-9]/g, "");
      if (clean && !originalWordsSet.has(clean)) {
        return (
          <span
            key={idx}
            className="bg-[#D1FAE5] text-emerald-900 px-0.5 rounded font-semibold dark:bg-emerald-950/40 dark:text-emerald-300"
          >
            {part}
          </span>
        );
      }
      return <span key={idx}>{part}</span>;
    });
  };

  const handleCopy = async () => {
    const textToCopy = viewMode === "latex" ? convertBlocksToLaTeX(nameText, contactText, blocks) : currentText;
    await navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = async () => {
    setPdfLoading(true);
    try {
      const plainText = isEditing ? parseLaTeXToPlainText(currentText) : currentText;
      const response = await fetch("/api/export/pdf/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: plainText }),
      });

      if (!response.ok) throw new Error("PDF download failed");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "resume-optimized-fasthire.pdf";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success("PDF Downloaded successfully! 📄");
    } catch (err: any) {
      toast.error(err.message || "Failed to download PDF.");
    } finally {
      setPdfLoading(false);
    }
  };

  const handleDownloadDOCX = async () => {
    setDocxLoading(true);
    try {
      const response = await fetch("/api/export/docx", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeId, text: currentText }),
      });

      if (!response.ok) throw new Error("DOCX download failed");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "resume-optimized-fasthire.docx";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success("DOCX Downloaded successfully! 📝");
    } catch (err: any) {
      toast.error(err.message || "Failed to download DOCX.");
    } finally {
      setDocxLoading(false);
    }
  };

  const handleReScore = async () => {
    setScoringLive(true);
    try {
      const plainText = isEditing ? parseLaTeXToPlainText(currentText) : currentText;
      const res = await fetch("/api/score", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeText: plainText, jobDescription })
      });
      if (res.ok) {
        const scoreData = await res.json();
        setLiveScore(scoreData.overall);
        if (onReScored) onReScored(scoreData.overall);
        if (onUpdateText) onUpdateText(plainText);
        toast.success(`Score updated to ${scoreData.overall}! 🎯`);
      }
    } catch (err) {
      toast.error("Re-scoring failed");
    } finally {
      setScoringLive(false);
    }
  };

  const latexCode = convertBlocksToLaTeX(nameText, contactText, blocks);

  return (
    <div className="bg-[#0b0c1e] border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col h-full">
      {/* Top Header Panel */}
      <div className="bg-[#0f112a] px-5 py-4 border-b border-white/5 flex flex-wrap gap-4 items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex bg-[#070814] border border-white/5 p-1 rounded-lg select-none">
            <button
              onClick={() => setViewMode("styled")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${viewMode === "styled" ? "bg-violet-600 text-white" : "text-slate-400 hover:text-white"
                }`}
            >
              <Eye className="h-3.5 w-3.5" />
              Styled View
            </button>
            <button
              onClick={() => setViewMode("latex")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${viewMode === "latex" ? "bg-violet-600 text-white" : "text-slate-400 hover:text-white"
                }`}
            >
              <Code className="h-3.5 w-3.5" />
              LaTeX Code
            </button>
          </div>

          {isEditing ? (
            <div className="flex items-center gap-2">
              <button
                onClick={handleCompile}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold transition-all shadow-md cursor-pointer"
              >
                <Play className="h-3.5 w-3.5 fill-current" />
                Run (Compile)
              </button>
              <button
                onClick={() => {
                  setCurrentText(text);
                  setIsEditing(false);
                }}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/5 bg-[#0b1c30] text-slate-400 hover:text-white text-xs font-bold transition-all cursor-pointer"
              >
                Cancel
              </button>
            </div>
          ) : (
            <button
              onClick={enterEditMode}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/5 bg-[#0b1c30] text-slate-400 hover:text-white text-xs font-bold transition-all cursor-pointer"
            >
              <Edit2 className="h-3.5 w-3.5" />
              Edit Resume
            </button>
          )}
        </div>

        {/* Action Downloads / Copy */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 text-xs font-bold px-3.5 py-2 rounded-xl transition-all text-slate-400 hover:text-white border border-white/5 bg-[#0b1c30] h-9"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied!" : "Copy Source"}
          </button>

          <Button
            onClick={handleDownloadPDF}
            disabled={pdfLoading}
            className="bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-xs h-9 rounded-xl flex items-center justify-center gap-1.5 px-4"
          >
            {pdfLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-4 w-4" />}
            Download PDF
          </Button>

          <Button
            onClick={handleDownloadDOCX}
            disabled={docxLoading}
            variant="outline"
            className="border-white/10 text-slate-300 hover:bg-white/5 font-bold text-xs h-9 rounded-xl flex items-center justify-center gap-1.5 px-4 bg-transparent"
          >
            {docxLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-4 w-4" />}
            Download DOCX
          </Button>
        </div>
      </div>

      {/* Editor & Live Scoring Alert panel */}
      {isEditing && (
        <div className="bg-cyan-950/20 border-b border-cyan-500/10 px-5 py-3 flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            {scoringLive ? (
              <Loader2 className="h-4 w-4 text-cyan-400 animate-spin" />
            ) : (
              <Play className="h-4 w-4 text-cyan-400" />
            )}
            <span className="text-[11px] text-slate-300 font-semibold leading-relaxed">
              {scoringLive ? "Re-calculating scores..." : "Edit mode active. Edits automatically request live scores in the background."}
              {liveScore !== null && (
                <span className="ml-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold px-2 py-0.5 rounded text-[10px]">
                  Live Score: {liveScore} 🎯
                </span>
              )}
            </span>
          </div>
          {currentText !== text && (
            <Button
              size="sm"
              onClick={handleCompile}
              className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-[10px] h-7 px-3 rounded-lg flex items-center gap-1"
            >
              <Play className="h-3 w-3 fill-current" />
              Compile & Preview
            </Button>
          )}
        </div>
      )}

      {/* Workspace Display Area */}
      <div className="flex-1 p-6 overflow-y-auto max-h-[650px] bg-[#070814] select-text">
        {isEditing ? (
          <textarea
            value={currentText}
            onChange={(e) => setCurrentText(e.target.value)}
            className="w-full h-full min-h-[500px] bg-[#0d0e22] text-slate-100 border border-white/5 rounded-xl p-5 font-mono text-xs focus:ring-1 focus:ring-violet-600 focus:outline-none resize-none leading-relaxed select-text"
          />
        ) : viewMode === "latex" ? (
          <div className="relative">
            <pre className="p-5 bg-[#0d0e22] border border-white/5 text-emerald-400 font-mono text-[11px] rounded-xl overflow-x-auto select-text whitespace-pre-wrap leading-relaxed">
              {latexCode}
            </pre>
          </div>
        ) : (
          /* Render visual styling matching the LaTeX-style PDF engine output */
          <div className="w-full max-w-4xl mx-auto bg-white text-slate-900 border border-slate-200 rounded-xl p-8 shadow-2xl font-serif select-text relative leading-normal">

            {blocks.map((block, idx) => {
              switch (block.type) {
                case "name":
                  return (
                    <h1 key={idx} className="text-xl font-bold text-center text-black mb-1 leading-normal select-text font-serif">
                      {block.text}
                    </h1>
                  );
                case "contact":
                  return (
                    <div key={idx} className="flex justify-center flex-wrap text-[9.5px] text-center text-slate-600 mb-3 leading-normal select-text font-serif">
                      {block.segments.map((seg, sIdx) => {
                        const el = seg.isLink && seg.url ? (
                          <a key={sIdx} href={seg.url} target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">
                            {seg.text}
                          </a>
                        ) : (
                          <span key={sIdx}>{seg.text}</span>
                        );
                        if (sIdx < block.segments.length - 1) {
                          return (
                            <React.Fragment key={sIdx}>
                              {el}
                              <span className="mx-1 text-slate-400">—</span>
                            </React.Fragment>
                          );
                        }
                        return el;
                      })}
                    </div>
                  );
                case "section":
                  return (
                    <h2 key={idx} className="text-xs font-bold text-black border-b border-black mt-3 mb-1.5 pb-0.5 leading-normal select-text font-serif">
                      {block.text}
                    </h2>
                  );
                case "summary":
                  return (
                    <p key={idx} className="text-[10px] mb-1 text-slate-800 leading-normal select-text font-serif">
                      {renderHighlightedText(block.text)}
                    </p>
                  );
                case "skillLine":
                  return (
                    <div key={idx} className="flex text-[10px] mb-1 leading-normal select-text font-serif">
                      <span className="font-bold text-black w-[140px] shrink-0">{block.label}:</span>
                      <span className="text-slate-800 flex-1">{renderHighlightedText(block.value)}</span>
                    </div>
                  );
                case "project":
                  return (
                    <div key={idx} className="mb-2">
                      <div className="flex justify-between text-[10.5px] font-bold text-black mb-0.5 leading-normal select-text font-serif">
                        <div className="flex items-center gap-1.5">
                          <span>{block.name}</span>
                          {block.projectUrl && (
                            <a href={block.projectUrl} target="_blank" rel="noopener noreferrer" className="text-[9.5px] text-blue-600 underline font-normal">
                              {block.projectUrl}
                            </a>
                          )}
                        </div>
                        {block.tech && (
                          <span className="font-normal italic text-slate-600">{renderHighlightedText(block.tech)}</span>
                        )}
                      </div>
                      {block.bullets.map((bullet, bIdx) => (
                        <div key={bIdx} className="flex items-start text-[10px] mb-0.5 pl-3 leading-normal select-text font-serif">
                          <span className="w-3 shrink-0 select-none text-black font-serif">•</span>
                          <span className="flex-1 text-slate-800 font-serif">{renderHighlightedText(bullet)}</span>
                        </div>
                      ))}
                    </div>
                  );
                case "job":
                  return (
                    <div key={idx} className="mb-2">
                      <div className="flex justify-between text-[10.5px] font-bold text-black mb-0.5 leading-normal select-text font-serif">
                        <span>{renderHighlightedText(block.title)}</span>
                        <span className="font-normal text-slate-700">{renderHighlightedText(block.dates)}</span>
                      </div>
                      <div className="text-[10px] italic text-slate-700 mb-1 leading-normal select-text font-serif">
                        {renderHighlightedText(block.company)}
                      </div>
                      {block.bullets.map((bullet, bIdx) => (
                        <div key={bIdx} className="flex items-start text-[10px] mb-0.5 pl-3 leading-normal select-text font-serif">
                          <span className="w-3 shrink-0 select-none text-black font-serif">•</span>
                          <span className="flex-1 text-slate-800 font-serif">{renderHighlightedText(bullet)}</span>
                        </div>
                      ))}
                    </div>
                  );
                case "education":
                  return (
                    <div key={idx} className="mb-2">
                      <div className="flex justify-between text-[10.5px] font-bold text-black mb-0.5 leading-normal select-text font-serif">
                        <span>{renderHighlightedText(block.degree)}</span>
                        <span className="font-normal text-slate-700">{renderHighlightedText(block.dates)}</span>
                      </div>
                      <div className="flex justify-between text-[10px] text-slate-800 leading-normal select-text font-serif">
                        <span>{renderHighlightedText(block.school)}</span>
                        <span>{renderHighlightedText(block.gpa)}</span>
                      </div>
                    </div>
                  );
                case "bullet":
                  return (
                    <div key={idx} className="flex items-start text-[10px] mb-0.5 pl-3 leading-normal select-text font-serif">
                      <span className="w-3 shrink-0 select-none text-black font-serif">•</span>
                      <span className="flex-1 text-slate-800 font-serif">{renderHighlightedText(block.text)}</span>
                    </div>
                  );
                case "cert":
                  return (
                    <div key={idx} className="text-[10px] text-slate-800 mb-0.5 leading-normal select-text font-serif">
                      {renderHighlightedText(block.text)}
                    </div>
                  );
                case "link":
                  return (
                    <a key={idx} href={block.url} target="_blank" rel="noopener noreferrer" className="text-[10px] text-blue-600 underline mb-0.5 block leading-normal select-text font-serif">
                      {block.label}
                    </a>
                  );
                case "spacer":
                  return <div key={idx} className="h-1" />;
                default:
                  return null;
              }
            })}
          </div>
        )}
      </div>
    </div>
  );
}
