"use client";

import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Loader2, Copy, Check, FileText, Edit2, Play, Eye, Code } from "lucide-react";
import { toast } from "react-hot-toast";

// Helper to strip markdown bold/italic tags
function cleanMarkdown(s: string): string {
  return s
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/`/g, "")
    .trim();
}

interface PDFLineNode {
  type: "name" | "contact" | "header" | "experience_title" | "experience_subtitle" | "bullet" | "body" | "spacer";
  text: string;
}

export function parseResumeToNodes(text: string): PDFLineNode[] {
  const rawLines = text.split(/\r?\n/);
  const nodes: PDFLineNode[] = [];
  let nameFound = false;

  // Phone regex matching format
  const phonePattern = /\b(?:\+?\d{1,3}[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b/;

  for (let i = 0; i < rawLines.length; i++) {
    const line = rawLines[i].trim();

    if (line === "") {
      nodes.push({ type: "spacer", text: "" });
      continue;
    }

    // 1. Detect Name (First non-empty line)
    if (!nameFound) {
      nodes.push({ type: "name", text: cleanMarkdown(line) });
      nameFound = true;
      continue;
    }

    // 2. Detect Contact
    const containsAt = line.includes("@");
    const containsPhone = phonePattern.test(line);
    const containsPipe = line.includes("|");

    if (containsAt || containsPhone || containsPipe) {
      if (containsPipe) {
        const parts = line.split("|").map(p => cleanMarkdown(p)).filter(Boolean);
        nodes.push({ type: "contact", text: parts.join("  |  ") });
      } else {
        nodes.push({ type: "contact", text: cleanMarkdown(line) });
      }
      continue;
    }

    // 3. Detect Section Header (ALL CAPS, length > 3, contains letters, no bullet markers)
    const isBulletMarker = /^[•\-\*\–\u2022]/.test(line);
    const hasLetters = /[A-Za-z]/.test(line);
    const isAllCaps = line === line.toUpperCase() && line.length > 3 && hasLetters && !isBulletMarker;

    if (isAllCaps) {
      nodes.push({ type: "header", text: cleanMarkdown(line) });
      continue;
    }

    // 4. Detect Bullet Point
    if (isBulletMarker) {
      const cleanBullet = cleanMarkdown(line.replace(/^[•\-\*\–\u2022\s]+/, ""));
      nodes.push({ type: "bullet", text: cleanBullet });
      continue;
    }

    // 5. Multi-line bullet continuation check
    const lastNode = nodes[nodes.length - 1];
    if (lastNode && lastNode.type === "bullet") {
      lastNode.text += " " + cleanMarkdown(line);
      continue;
    }

    // 6. Experience Block Detection
    if (line.includes("|")) {
      const parts = line.split("|").map(p => cleanMarkdown(p)).filter(Boolean);
      nodes.push({ type: "experience_title", text: parts.join(" | ") });
      
      let nextLineIndex = i + 1;
      while (nextLineIndex < rawLines.length && rawLines[nextLineIndex].trim() === "") {
        nextLineIndex++;
      }
      if (nextLineIndex < rawLines.length) {
        const nextLine = rawLines[nextLineIndex].trim();
        if (nextLine.includes("|") && !nextLine.includes("@") && !phonePattern.test(nextLine)) {
          const subParts = nextLine.split("|").map(p => cleanMarkdown(p)).filter(Boolean);
          nodes.push({ type: "experience_subtitle", text: subParts.join(" | ") });
          i = nextLineIndex;
          continue;
        }
      }
      continue;
    }

    // Default fallback: render as normal text paragraph
    nodes.push({ type: "body", text: cleanMarkdown(line) });
  }

  return nodes;
}

// Convert nodes to professional LaTeX format code
export function convertNodesToLaTeX(name: string, contactLine: string, nodes: PDFLineNode[]): string {
  let latex = `% LaTeX Resume generated by FastHire AI
\\documentclass[letterpaper,11pt]{article}
\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}

\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.0in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\textbf{\\Huge ${escapeLaTeX(name)}}} \\\\ \\vspace{4pt}
    \\small ${escapeLaTeX(contactLine)}
\\end{center}

`;

  let inList = false;

  for (const node of nodes) {
    if (node.type === "name" || node.type === "contact" || node.type === "spacer") {
      continue;
    }

    if (node.type === "header") {
      if (inList) {
        latex += "\\end{itemize}\n\\vspace{-5pt}\n";
        inList = false;
      }
      latex += `\n\\section{${escapeLaTeX(node.text)}}\n`;
    } else if (node.type === "experience_title") {
      if (inList) {
        latex += "\\end{itemize}\n\\vspace{-5pt}\n";
        inList = false;
      }
      latex += `\\vspace{4pt}\n\\textbf{${escapeLaTeX(node.text)}}\\\\\n`;
    } else if (node.type === "experience_subtitle") {
      latex += `{\\small \\textit{${escapeLaTeX(node.text)}}}\\\\\n`;
    } else if (node.type === "bullet") {
      if (!inList) {
        latex += "\\begin{itemize}[leftmargin=0.15in, label=\\textbullet]\n";
        inList = true;
      }
      latex += `  \\item ${escapeLaTeX(node.text)}\n`;
    } else if (node.type === "body") {
      if (inList) {
        latex += "\\end{itemize}\n\\vspace{-5pt}\n";
        inList = false;
      }
      latex += `${escapeLaTeX(node.text)}\\\\\n`;
    }
  }

  if (inList) {
    latex += "\\end{itemize}\n";
  }

  latex += "\n\\end{document}\n";
  return latex;
}

function escapeLaTeX(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/~/g, "\\textasciitilde")
    .replace(/\^/g, "\\textasciicircum");
}

interface ResumeViewerProps {
  text: string;
  originalText?: string;
  resumeId: string;
  type: "original" | "optimized";
  jobDescription: string;
  onUpdateText?: (newText: string) => void;
  onReScored?: (newScore: number) => void;
}

export default function ResumeViewer({
  text,
  originalText,
  resumeId,
  type,
  jobDescription,
  onUpdateText,
  onReScored
}: ResumeViewerProps) {
  const [currentText, setCurrentText] = useState(text);
  const [isEditing, setIsEditing] = useState(false);
  const [viewMode, setViewMode] = useState<"styled" | "latex">("styled");
  const [copied, setCopied] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [docxLoading, setDocxLoading] = useState(false);

  // Live scoring state
  const [liveScore, setLiveScore] = useState<number | null>(null);
  const [scoringLive, setScoringLive] = useState(false);

  useEffect(() => {
    setCurrentText(text);
    setLiveScore(null);
  }, [text]);

  // Debounced live scoring (800ms)
  useEffect(() => {
    if (type !== "optimized" || !isEditing) return;

    const handler = setTimeout(async () => {
      if (!currentText.trim() || currentText === text) {
        setLiveScore(null);
        return;
      }
      setScoringLive(true);
      try {
        const res = await fetch("/api/score", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ resumeText: currentText, jobDescription })
        });
        if (res.ok) {
          const scoreData = await res.json();
          setLiveScore(scoreData.overall);
        }
      } catch (err) {
        console.error("Live score check failed:", err);
      } finally {
        setScoringLive(false);
      }
    }, 800);

    return () => clearTimeout(handler);
  }, [currentText, isEditing, type, text, jobDescription]);

  // Parse nodes for rendering
  const nodes = parseResumeToNodes(currentText);

  // Extract name and contact for header
  const nameNode = nodes.find(n => n.type === "name");
  const contactNode = nodes.find(n => n.type === "contact");
  const nameText = nameNode ? nameNode.text : "Resume Document";
  const contactText = contactNode ? contactNode.text : "";

  // Set up original words Set for diff highlighting
  const originalClean = (originalText || "").toLowerCase().replace(/[^a-z0-9\s]/g, " ");
  const originalWordsSet = new Set(originalClean.split(/\s+/).filter(Boolean));

  // Word-by-word diff highlighter helper
  const renderHighlightedText = (lineText: string) => {
    if (type !== "optimized" || !originalText || originalWordsSet.size === 0) {
      return <span>{lineText}</span>;
    }
    const parts = lineText.split(/(\s+)/);
    return parts.map((part, idx) => {
      if (/^\s+$/.test(part)) {
        return <span key={idx}>{part}</span>;
      }
      const clean = part.toLowerCase().replace(/[^a-z0-9]/g, "");
      if (clean && !originalWordsSet.has(clean)) {
        return (
          <span
            key={idx}
            className="bg-[#D1FAE5] text-emerald-900 px-0.5 rounded font-semibold dark:bg-emerald-950/40 dark:text-emerald-300"
          >
            {part}
          </span>
        );
      }
      return <span key={idx}>{part}</span>;
    });
  };

  const handleCopy = async () => {
    const textToCopy = viewMode === "latex" ? convertNodesToLaTeX(nameText, contactText, nodes) : currentText;
    await navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = async () => {
    setPdfLoading(true);
    try {
      const response = await fetch("/api/export/pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeId, type, text: currentText }),
      });

      if (!response.ok) throw new Error("PDF download failed");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = type === "original" ? "resume-original.pdf" : "resume-optimized-fasthire.pdf";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success("PDF Downloaded successfully! 📄");
    } catch (err: any) {
      toast.error(err.message || "Failed to download PDF.");
    } finally {
      setPdfLoading(false);
    }
  };

  const handleDownloadDOCX = async () => {
    setDocxLoading(true);
    try {
      const response = await fetch("/api/export/docx", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeId, text: currentText }),
      });

      if (!response.ok) throw new Error("DOCX download failed");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "resume-optimized-fasthire.docx";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success("DOCX Downloaded successfully! 📝");
    } catch (err: any) {
      toast.error(err.message || "Failed to download DOCX.");
    } finally {
      setDocxLoading(false);
    }
  };

  const handleReScore = async () => {
    if (currentText === text) return;
    setScoringLive(true);
    try {
      const res = await fetch("/api/score", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeText: currentText, jobDescription })
      });
      if (res.ok) {
        const scoreData = await res.json();
        setLiveScore(scoreData.overall);
        if (onReScored) onReScored(scoreData.overall);
        if (onUpdateText) onUpdateText(currentText);
        toast.success(`Score updated to ${scoreData.overall}! 🎯`);
      }
    } catch (err) {
      toast.error("Re-scoring failed");
    } finally {
      setScoringLive(false);
    }
  };

  const latexCode = convertNodesToLaTeX(nameText, contactText, nodes);

  return (
    <div className="bg-[#0b0c1e] border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col h-full">
      {/* Top Header Panel */}
      <div className="bg-[#0f112a] px-5 py-4 border-b border-white/5 flex flex-wrap gap-4 items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex bg-[#070814] border border-white/5 p-1 rounded-lg select-none">
            <button
              onClick={() => setViewMode("styled")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                viewMode === "styled" ? "bg-violet-600 text-white" : "text-slate-400 hover:text-white"
              }`}
            >
              <Eye className="h-3.5 w-3.5" />
              Styled View
            </button>
            <button
              onClick={() => setViewMode("latex")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all ${
                viewMode === "latex" ? "bg-violet-600 text-white" : "text-slate-400 hover:text-white"
              }`}
            >
              <Code className="h-3.5 w-3.5" />
              LaTeX Code
            </button>
          </div>

          {type === "optimized" && (
            <button
              onClick={() => setIsEditing(!isEditing)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-bold transition-all ${
                isEditing ? "bg-cyan-500/10 border-cyan-500/30 text-cyan-400" : "bg-[#0b1c30] border-white/5 text-slate-400 hover:text-white"
              }`}
            >
              <Edit2 className="h-3.5 w-3.5" />
              {isEditing ? "Stop Editing" : "Edit Resume"}
            </button>
          )}
        </div>

        {/* Action Downloads / Copy */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 text-xs font-bold px-3.5 py-2 rounded-xl transition-all text-slate-400 hover:text-white border border-white/5 bg-[#0b1c30] h-9"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied!" : "Copy Source"}
          </button>
          
          <Button
            onClick={handleDownloadPDF}
            disabled={pdfLoading}
            className="bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-xs h-9 rounded-xl flex items-center justify-center gap-1.5 px-4"
          >
            {pdfLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-4 w-4" />}
            Download PDF
          </Button>

          {type === "optimized" && (
            <Button
              onClick={handleDownloadDOCX}
              disabled={docxLoading}
              variant="outline"
              className="border-white/10 text-slate-300 hover:bg-white/5 font-bold text-xs h-9 rounded-xl flex items-center justify-center gap-1.5 px-4 bg-transparent"
            >
              {docxLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-4 w-4" />}
              Download DOCX
            </Button>
          )}
        </div>
      </div>

      {/* Editor & Live Scoring Alert panel */}
      {isEditing && (
        <div className="bg-cyan-950/20 border-b border-cyan-500/10 px-5 py-3 flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            {scoringLive ? (
              <Loader2 className="h-4 w-4 text-cyan-400 animate-spin" />
            ) : (
              <Play className="h-4 w-4 text-cyan-400" />
            )}
            <span className="text-[11px] text-slate-300 font-semibold leading-relaxed">
              {scoringLive ? "Re-calculating scores..." : "Edit mode active. Edits automatically request live scores in the background."}
              {liveScore !== null && (
                <span className="ml-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold px-2 py-0.5 rounded text-[10px]">
                  Live Score: {liveScore} 🎯
                </span>
              )}
            </span>
          </div>
          {currentText !== text && (
            <Button
              size="sm"
              onClick={handleReScore}
              className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-[10px] h-7 px-3 rounded-lg"
            >
              Re-score My Edits
            </Button>
          )}
        </div>
      )}

      {/* Workspace Display Area */}
      <div className="flex-1 p-6 overflow-y-auto max-h-[650px] bg-[#070814] select-text">
        {isEditing ? (
          <textarea
            value={currentText}
            onChange={(e) => setCurrentText(e.target.value)}
            className="w-full h-full min-h-[500px] bg-[#0d0e22] text-slate-100 border border-white/5 rounded-xl p-5 font-mono text-xs focus:ring-1 focus:ring-violet-600 focus:outline-none resize-none leading-relaxed select-text"
          />
        ) : viewMode === "latex" ? (
          <div className="relative">
            <pre className="p-5 bg-[#0d0e22] border border-white/5 text-emerald-400 font-mono text-[11px] rounded-xl overflow-x-auto select-text whitespace-pre-wrap leading-relaxed">
              {latexCode}
            </pre>
          </div>
        ) : (
          /* Render visual styling matching the LaTeX-style PDF engine output */
          <div className="w-full max-w-4xl mx-auto bg-white text-slate-900 border border-slate-200 rounded-xl p-8 shadow-2xl font-sans select-text relative leading-normal">
            
            {nodes.map((node, idx) => {
              switch (node.type) {
                case "name":
                  return (
                    <h1 key={idx} className="text-xl font-bold text-center text-black mb-1 leading-normal select-text">
                      {node.text}
                    </h1>
                  );
                case "contact":
                  return (
                    <div key={idx} className="text-[9.5px] text-center text-slate-600 mb-3 leading-normal select-text">
                      {node.text}
                    </div>
                  );
                case "header":
                  return (
                    <h2 key={idx} className="text-xs font-bold text-black uppercase border-b border-black mt-3 mb-1.5 pb-0.5 leading-normal select-text">
                      {node.text}
                    </h2>
                  );
                case "experience_title":
                  return (
                    <div key={idx} className="text-[10.5px] font-bold text-black mb-0.5 leading-normal select-text">
                      {renderHighlightedText(node.text)}
                    </div>
                  );
                case "experience_subtitle":
                  return (
                    <div key={idx} className="text-[10px] text-slate-500 mb-1 leading-normal select-text">
                      {renderHighlightedText(node.text)}
                    </div>
                  );
                case "bullet":
                  return (
                    <div key={idx} className="flex items-start text-[10px] mb-0.5 pl-3 leading-normal select-text">
                      <span className="w-3 shrink-0 select-none text-black">•</span>
                      <span className="flex-1 text-slate-800">{renderHighlightedText(node.text)}</span>
                    </div>
                  );
                case "spacer":
                  return <div key={idx} className="h-1" />;
                default:
                  return (
                    <p key={idx} className="text-[10px] mb-1 text-slate-800 leading-normal select-text">
                      {renderHighlightedText(node.text)}
                    </p>
                  );
              }
            })}

          </div>
        )}
      </div>
    </div>
  );
}
